### ISSUE TITLE
Different browsers give different boards

### ISSUE THREAD

**Issue by xupwup** [psidex/sedordle#1]
When opened in chrome, i get these words:
ONSET, SNEAK, ALERT, VIXEN, AGORA, STEEL, AROSE, STASH, OFTEN, BLUSH, FORUM, SNACK, FEMME, TABBY, STOCK, ADULT
When opened in firefox:
ONSET, SNEAK, ALERT, VIXEN, AGORA, STEEL, AROSE, STASH, OFTEN, BLUSH, FORUM, SNACK, ENEMY, POWER, STAID, RIGOR

Maybe Math.sin function is different, causing this function to behave differently?
Math.seed = (s) => () => {
  // eslint-disable-next-line no-param-reassign
  s = Math.sin(s) * 10000; return s - Math.floor(s);
};

Nice game by the way :)

**Comment by psidex** [comment]
Yeah I'm seeing that behaviour as well, I think you're right.

I wrote up a quick test to see if it's `Math.sin` and it seems like it is:

```js
const sined = [];
let s = 123456789;
for (let i = 0; i < 40; i++) {
  const calced = Math.sin(s);
  sined.push(calced);
  s = calced;
}
console.log(sined);
```

![image](https://user-images.githubusercontent.com/14183909/158036762-2872bbca-c2ff-4d68-83e5-e1e44998422e.png)

Not sure how to get around this, I guess pick a different seeded random function? I'll have a think.

Thanks for opening the issue!
