### ISSUE TITLE
Game reset time seems to be midnight UTC instead of midnight local

### ISSUE THREAD

**Issue by rhtorchia** [psidex/sedordle#2]
If you click on the (?), the info text says: _Sedordle resets at midnight in your timezone._

Actual reset time seems to be midnight UTC. It might be hard-coded to change at 0:00 UTC, or, assuming the server is with you in England, it might be grabbing the local time of the server instead of the client.

I'm in PDT where it's currently 9:00PM on March 15th. The new puzzle went live sometime in the past six hours. I just checked, and the Share button text is already populated with the date 2022-03-16.

Unless there's a compelling reason to have it reset at midnight local, the easiest fix is probably just to change the info text to say midnight UTC.

**Comment by psidex** [comment]
Yeah it does seem to be that way, I just sort of assumed that the method I was using would be local time...

Not sure if I'll change it, but yeah I'll update the info text.

Thanks
