### ISSUE TITLE
Duplicate words as answers

### ISSUE THREAD

**Issue by evanbaldonado** [psidex/sedordle#4]
Currently, Sedordle can have the same word as an answer multiple times in the same game. I'm not sure if this was meant to be an intended feature, but I wanted to flag this in case you weren't already aware.

Example from Sedordle 2022-03-21:

12-05-06-08
10-**03**-09-15
14-17-07-04
11-**03**-13-16

**Comment by psidex** [comment]
Yeah, I just assumed that there were enough target words to not cause conflicts but apparently not! I'll fix it asap
